# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from engula.v1 import engula_pb2 as engula_dot_v1_dot_engula__pb2


class EngulaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Batch = channel.unary_unary(
                '/engula.v1.Engula/Batch',
                request_serializer=engula_dot_v1_dot_engula__pb2.BatchRequest.SerializeToString,
                response_deserializer=engula_dot_v1_dot_engula__pb2.BatchResponse.FromString,
                )


class EngulaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngulaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=engula_dot_v1_dot_engula__pb2.BatchRequest.FromString,
                    response_serializer=engula_dot_v1_dot_engula__pb2.BatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engula.v1.Engula', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Engula(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engula.v1.Engula/Batch',
            engula_dot_v1_dot_engula__pb2.BatchRequest.SerializeToString,
            engula_dot_v1_dot_engula__pb2.BatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
