# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engula/v1/engula.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from engula.v1 import database_pb2 as engula_dot_v1_dot_database__pb2
from engula.v1 import universe_pb2 as engula_dot_v1_dot_universe__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65ngula/v1/engula.proto\x12\tengula.v1\x1a\x18\x65ngula/v1/database.proto\x1a\x18\x65ngula/v1/universe.proto\"l\n\x0c\x42\x61tchRequest\x12-\n\tdatabases\x18\x01 \x03(\x0b\x32\x1a.engula.v1.DatabaseRequest\x12-\n\tuniverses\x18\x02 \x03(\x0b\x32\x1a.engula.v1.UniverseRequest\"o\n\rBatchResponse\x12.\n\tdatabases\x18\x01 \x03(\x0b\x32\x1b.engula.v1.DatabaseResponse\x12.\n\tuniverses\x18\x02 \x03(\x0b\x32\x1b.engula.v1.UniverseResponse2F\n\x06\x45ngula\x12<\n\x05\x42\x61tch\x12\x17.engula.v1.BatchRequest\x1a\x18.engula.v1.BatchResponse\"\x00\x62\x06proto3')



_BATCHREQUEST = DESCRIPTOR.message_types_by_name['BatchRequest']
_BATCHRESPONSE = DESCRIPTOR.message_types_by_name['BatchResponse']
BatchRequest = _reflection.GeneratedProtocolMessageType('BatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHREQUEST,
  '__module__' : 'engula.v1.engula_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.BatchRequest)
  })
_sym_db.RegisterMessage(BatchRequest)

BatchResponse = _reflection.GeneratedProtocolMessageType('BatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATCHRESPONSE,
  '__module__' : 'engula.v1.engula_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.BatchResponse)
  })
_sym_db.RegisterMessage(BatchResponse)

_ENGULA = DESCRIPTOR.services_by_name['Engula']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATCHREQUEST._serialized_start=89
  _BATCHREQUEST._serialized_end=197
  _BATCHRESPONSE._serialized_start=199
  _BATCHRESPONSE._serialized_end=310
  _ENGULA._serialized_start=312
  _ENGULA._serialized_end=382
# @@protoc_insertion_point(module_scope)
